/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB LED',
        RGB_DIGITAL: 'RGB Lamp Red#%1 R_state%2 Green#%3 G_State%4 Blue#%5 B_State%6',
        RGB_ANALOG: 'RGB Lamp Red#%1 R_analogWrite%2 Green#%3 G_analogWrite%4 Blue#%5 B_analogWrite%6',
        BUZZER_CATEGORY: 'Passive buzzer',
        BUZZER_TONE: 'Tone PIN#%1 frequency%2',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'noTone%1',
     
        LM35_CATEGORY: 'Temperature',
        LM35_READ_TEMPERATURE: 'LM35 read temperature PIN: %1',
        IR_CATEGORY: 'IR Remote',
        IRSEND_CATEGORY: 'IR Send',
        IR_SEND: 'IRsend %1 PIN#%2 data%3 bits%4',
        IR_SEND_RAW: 'IRsend(RAW) PIN#%1 Array%2 listLength%3 frequency%4',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
  
        ADXL345_CATEGORY: 'Acceleration',
        ADXL345_READ: 'ADXL345 read %1',
        DHT_CATEGORY: 'DHT',
        DHT_INIT: 'Init dht %1 pin %2 mode %3',
        DHT_READ_TEMPERATURE: 'Dht %1 read temperature %2',
        DHT_READ_HUMIDITY: 'Dht %1 read humidity',
        KSENCODER_CATEGORY: 'Encoder',
        KSENCODER_INIT: 'Init encoder %1 DT %2 CLK %3',
        KSENCODER_READ: 'Read encoder %1',
        KSENCODER_WRITE: 'Encoder %1 write %2',
        KSENCODER_BUTTON: 'Read the rotary encoder button PIN# %1',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        JOYSTICK_CATEGORY: 'JoyStick',
        JOYSTICK_Z_STATE: 'Interface %1 joystick button(Z) was be pushed?',
        JOYSTICK_XY_VALUE: 'read interface %1 joystick %2 axis',
        X: 'X',
        Y :'Y',
        FOURDIGITCLOCKDISPLAY_CATEGORY: '4-Digit Display',
        FOURDIGITCLOCKDISPLAY_INIT: 'init 4-digit display pin DIO %1 CLK %2',
        FOURDIGITCLOCKDISPLAY_SETBRIGHTNESS: 'set brightness %1',
        FOURDIGITCLOCKDISPLAY_DISPLAYNUMBER: 'display number %1',
        FOURDIGITCLOCKDISPLAY_DISPLAYSTRING: 'display string %1',
        FOURDIGITCLOCKDISPLAY_DISPLAY: 'display %1 at bit %2',
        FOURDIGITCLOCKDISPLAY_SETPOINT: 'set point %1',
        FOURDIGITCLOCKDISPLAY_STATE_ON: 'on',
        FOURDIGITCLOCKDISPLAY_STATE_OFF: 'off',
        FOURDIGITCLOCKDISPLAY_SETPOINT_TOOLTIP: 'It will take effect after the next update of the display.',
        FOURDIGITCLOCKDISPLAY_CLEAR: 'clear'
       
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB灯',
        RGB_DIGITAL: 'RGB灯 红#%1 电平为%2 绿#%3 电平为%4 蓝#%5 电平为%6',
        RGB_ANALOG: 'RGB灯 红#%1 模拟输出%2 绿#%3 模拟输出%4 蓝#%5 模拟输出%6',
     
        BUZZER_CATEGORY: '无源蜂鸣器',
        BUZZER_TONE: '播放声音 引脚%1 频率%2',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '蜂鸣器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
      
        LM35_CATEGORY: '温度',
        LM35_READ_TEMPERATURE: '读取LM35温度值 引脚：%1',
        IRSEND_CATEGORY: '红外发射',
        IR_SEND: '红外发射（%1)引脚%2 数值%3 比特数%4',
        IR_SEND_RAW: '红外发射(RAW)引脚%1 数组%2 数组长度%3 频率%4',
        IR_CATEGORY: '红外接收',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        ADXL345_CATEGORY: '加速度',
        ADXL345_READ: '读取ADXL345 %1',
        DHT_CATEGORY: '温湿度',
        DHT_INIT: '初始化 dht %1 引脚 %2 型号 %3',
        DHT_READ_TEMPERATURE: 'dht %1 读取温度 %2',
        DHT_READ_HUMIDITY: 'dht %1 读取湿度',
     
        KSENCODER_CATEGORY: '旋转编码器',
        KSENCODER_INIT: '初始化 旋转编码器 %1 引脚DT %2 CLK %3',
        KSENCODER_READ: '读取 旋转编码器 %1',
        KSENCODER_WRITE: '旋转编码器 %1 赋值为 %2',
        KSENCODER_BUTTON: '读旋转编码器按钮值 引脚# %1',
        HC_SR04_CATEGORY: '超声波',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        JOYSTICK_CATEGORY: '摇杆',
        JOYSTICK_Z_STATE: '接口%1摇杆按钮(Z)被按下',
        JOYSTICK_XY_VALUE: '读取接口%1摇杆%2轴',
        X: 'X',
        Y :'Y',
        FOURDIGITCLOCKDISPLAY_CATEGORY: '4位数码管',
        FOURDIGITCLOCKDISPLAY_INIT: '初始化4位数码管引脚 DIO %1 CLK %2',
        FOURDIGITCLOCKDISPLAY_SETBRIGHTNESS: '设置亮度 %1',
        FOURDIGITCLOCKDISPLAY_DISPLAYNUMBER: '显示数字 %1',
        FOURDIGITCLOCKDISPLAY_DISPLAYSTRING: '显示字符 %1',
        FOURDIGITCLOCKDISPLAY_DISPLAY: '显示 %1 第 %2 位',
        FOURDIGITCLOCKDISPLAY_SETPOINT: '设置点 %1',
        FOURDIGITCLOCKDISPLAY_STATE_ON: '开',
        FOURDIGITCLOCKDISPLAY_STATE_OFF: '关',
        FOURDIGITCLOCKDISPLAY_SETPOINT_TOOLTIP: '将在下次更新显示后生效.',
        FOURDIGITCLOCKDISPLAY_CLEAR: '清空'
        
    });
    return Blockly;
}

exports = addMsg;
