/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB LED',
        RGB_DIGITAL: 'RGB Lamp Red#%1 R_state%2 Green#%3 G_State%4 Blue#%5 B_State%6',
        RGB_ANALOG: 'RGB Lamp Red#%1 R_analogWrite%2 Green#%3 G_analogWrite%4 Blue#%5 B_analogWrite%6',
        KS_74HC595_CATEGORY: '74HC595',
        KS_74HC595_INIT: 'Init 74HC595 ST_CP%1 SH_CP%2 DS%3',
        KS_74HC595_OUTPUT: '74HC595 output Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
        BUZZER_CATEGORY: 'Passive buzzer',
        BUZZER_TONE: 'Tone PIN#%1 frequency%2',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'noTone%1',
        KS_SERVO_CATEGORY: 'servo',
        KS_SERVO_ANGLE: 'Servo PIN#%1 degree%2 delay%3',
        KS_SERVO_READ: 'Servo PIN#%1 read degree',
        KS_STEPPER_CATEGORY: 'Stepper',
        KS_STEPPER_INIT: 'Init IN1#%1 IN2%2 IN3%3 IN4%4 Steps per revolution%5 speed%6',
        KS_STEPPER_STEP: 'Stepper step%1',
        LM35_CATEGORY: 'Temperature',
        LM35_READ_TEMPERATURE: 'LM35 read temperature PIN: %1',
        IR_CATEGORY: 'IR Remote',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
        ONETUBE_CATEGORY: '1 Digital Tube',
        ONEINIT: 'Init One digital tube PIN a~dp:4~11',
        ONETUBE_NUMBER: 'One digital_tube display data(0~9)%1 dot%2',
        PINFOURTUBE_CATEGORY: '4 Digital Tube',
        PINFOURTUBE_INIT: '4 Digital Tube Init a~dp:1~8 digits 1~4:9~12',
        PINFOURTUBE_STRING: '4 digital display data %1 Decimal point%2',
        MATRIX_PIN_CATEGORY: '8x8 Matrix',
        MATRIX_PIN_INIT: 'Init Matrix 8*8 row:2~9 column:10~A3',
        MATRIX_PIN_NUMBER: 'Matrix 8*8 display%1',
        LCD_PIN_CATEGORY: 'LCD',
        LCD_PIN_INIT: 'Init lcd1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
        LCD_PIN_PRINT: 'lcd1602 row%1 column%2 print %3',
        LCD_PIN_CLEAR: 'lcd1602 %1',

        LCD_PIN_SATE_ON: 'on',
        LCD_PIN_SATE_OFF: 'off',
        LCD_PIN_SETCURSORSTYLE: 'Set lcd cursor %1 style %2',
        LCD_PIN_SATE_DISPLAY: 'Display',
        LCD_PIN_SATE_HIDE: 'Hide',
        LCD_PIN_STYLE_BLINK: 'Blink',
        LCD_PIN_STYLE_NOBLINK: 'No-blink',
        ADXL345_CATEGORY: 'Acceleration',
        ADXL345_READ: 'ADXL345 read %1',
        DHT_CATEGORY: 'DHT',
        DHT_INIT: 'Init dht %1 pin %2 mode %3',
        DHT_READ_TEMPERATURE: 'Dht %1 read temperature %2',
        DHT_READ_HUMIDITY: 'Dht %1 read humidity',
        DS3231_CATEGORY: 'Clock',
        DS3231_INIT: 'Init DS3231',
        DS3231_SET_SYS_TIME: 'Set to the current system time',
        DS3231_SET_TIME: 'Set time year%1 month%2 date%3 hour%4 minute%5 second%6',
        DS3231_READ: 'DS3231 read %1',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        JOYSTICK_CATEGORY: 'JoyStick',
        JOYSTICK_Z_STATE: 'Interface %1 joystick button(Z) was be pushed?',
        JOYSTICK_XY_VALUE: 'read interface %1 joystick %2 axis',
        X: 'X',
        Y :'Y',
        MFRC522_CATEGORY: 'RFID',
        MFRC522_INIT: 'init mfrc522 pin CS %1 RST %2',
        MFRC522_ISNEWCARDPRESENT: 'new card present?',
        MFRC522_READCARDSERIAL: 'mfrc522 successfully read card serial number?',
        MFRC522_GETCARDTYPENAME: 'mfrc522 get card type name',
        MFRC522_GETCARDUID: 'mfrc522 get card UID',
        MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 to hex string',
        MFRC522_SETKEY: 'mfrc522 set secret key %1',
        MFRC522_VERIFICATIONKEY: 'mfrc522 verification block %1 key is correct?',
        MFRC522_READBLOCKDATA: 'mfrc522 read block %1',
        MFRC522_GETBLOCKDATA: 'mfrc522 block data (type %1)',
        MFRC522_DATATYPE_NUBMER: 'number',
        MFRC522_DATATYPE_STRING: 'string',
        MFRC522_GETBLOCKDATA_TOOLTIP: 'String length less than 16 byte.',
        MFRC522_WRITEBLOCKDATA: 'mfrc522 write %1 to block %2 (type %3)',
        MFRC522_WRITEKEYTOSECTOR: 'mfrc522 write key %1 to sector %2',
        MFRC522_PRINTSECTORDATA: 'mfrc522 print sector %1 data',
        MFRC522_HALT: 'mfrc522 halt'
       
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        RGB_CATEGORY: 'RGB灯',
        RGB_DIGITAL: 'RGB灯 红#%1 电平为%2 绿#%3 电平为%4 蓝#%5 电平为%6',
        RGB_ANALOG: 'RGB灯 红#%1 模拟输出%2 绿#%3 模拟输出%4 蓝#%5 模拟输出%6',
        KS_74HC595_CATEGORY: '74HC595',
        KS_74HC595_INIT: '初始化 74HC595 ST_CP%1 SH_CP%2 DS%3',
        KS_74HC595_OUTPUT: '74HC595 输出 Q1%1 Q2%2 Q3%3 Q4%4 Q5%5 Q6%6 Q7%7 Q8%8',
        BUZZER_CATEGORY: '无源蜂鸣器',
        BUZZER_TONE: '播放声音 引脚%1 频率%2',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '蜂鸣器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 角度%2 延时(毫秒)%3',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        KS_STEPPER_CATEGORY: '步进电机',
        KS_STEPPER_INIT: '初始化 IN1%1 IN2%2 IN3%3 IN4%4 每转步数%5 速度%6',
        KS_STEPPER_STEP: '步进电机 运转步数%1',
        LM35_CATEGORY: '温度',
        LM35_READ_TEMPERATURE: '读取LM35温度值 引脚：%1',
        IR_CATEGORY: '红外接收',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        ONETUBE_CATEGORY: '1位数码管',
        ONEINIT: '初始化一位数码管 引脚a~dp:4~11',
        ONETUBE_NUMBER: '一位数码管显示数字(0~9)%1 小数点%2',
        PINFOURTUBE_CATEGORY: '4位数码管',
        PINFOURTUBE_INIT: '初始化4位数码管 a~dp:1~8 位1~4:9~12',
        PINFOURTUBE_STRING: '数码管数字%1 小数位数%2',
        MATRIX_PIN_CATEGORY: '8*8点阵',
        MATRIX_PIN_INIT: '初始化 8*8点阵 行2~9 列10~A3',
        MATRIX_PIN_NUMBER: '点阵 显示%1',
        LCD_PIN_CATEGORY: '液晶屏',
        LCD_PIN_INIT: '初始化 LCD1602 RS%1 EN%2 D4%3 D5%4 D6%5 D7%6',
        LCD_PIN_PRINT: 'LCD1602 在第%1行 第%2列 打印%3',
        LCD_PIN_CLEAR: 'LCD1602显示屏%1',

        LCD_PIN_SATE_ON: '开',
        LCD_PIN_SATE_OFF: '关',
        LCD_PIN_SETCURSORSTYLE: '设置 lcd 光标 %1 样式 %2',
        LCD_PIN_SATE_DISPLAY: '显示',
        LCD_PIN_SATE_HIDE: '隐藏',
        LCD_PIN_STYLE_BLINK: '闪烁',
        LCD_PIN_STYLE_NOBLINK: '不闪烁',
        ADXL345_CATEGORY: '加速度',
        ADXL345_READ: '读取ADXL345 %1',
        DHT_CATEGORY: '温湿度',
        DHT_INIT: '初始化 dht %1 引脚 %2 型号 %3',
        DHT_READ_TEMPERATURE: 'dht %1 读取温度 %2',
        DHT_READ_HUMIDITY: 'dht %1 读取湿度',
        DS3231_CATEGORY: '时钟',
        DS3231_INIT: '初始化 DS3231时钟',
        DS3231_SET_SYS_TIME: '设置为当前系统时间',
        DS3231_SET_TIME: '设置自定义时间 年%1 月%2 日%3 时%4 分%5 秒%6',
        DS3231_READ: 'DS3231 读取时间 %1',
        HC_SR04_CATEGORY: '超声波',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        JOYSTICK_CATEGORY: '摇杆',
        JOYSTICK_Z_STATE: '接口%1摇杆按钮(Z)被按下',
        JOYSTICK_XY_VALUE: '读取接口%1摇杆%2轴',
        X: 'X',
        Y :'Y',
        MFRC522_CATEGORY: 'RFID',
        MFRC522_INIT: '初始化 mfrc522 引脚 CS %1 RST %2',
        MFRC522_ISNEWCARDPRESENT: '是否有新卡?',
        MFRC522_READCARDSERIAL: 'mfrc522 成功读取到卡序列号?',
        MFRC522_GETCARDTYPENAME: 'mfrc522 获取卡类型名称',
        MFRC522_GETCARDUID: 'mfrc522 获取卡 UID',
        MFRC522_NUMBERTOHEXSTRING: 'mfrc522 %1 转为16进制字符串',
        MFRC522_SETKEY: 'mfrc522 设置密钥 %1',
        MFRC522_VERIFICATIONKEY: 'mfrc522 验证块 %1 密码正确？',
        MFRC522_READBLOCKDATA: 'mfrc522 读取块 %1',
        MFRC522_GETBLOCKDATA: 'mfrc522 块数据 (类型 %1)',
        MFRC522_DATATYPE_NUBMER: '数字',
        MFRC522_DATATYPE_STRING: '字符串',
        MFRC522_GETBLOCKDATA_TOOLTIP: '字符串长度小于 16 字节。',
        MFRC522_WRITEBLOCKDATA: 'mfrc522 写 %1 到块 %2 (类型 %3)',
        MFRC522_WRITEKEYTOSECTOR: 'mfrc522 写密码 %1 到扇区 %2',
        MFRC522_PRINTSECTORDATA: 'mfrc522 打印扇区 %1 数据',
        MFRC522_HALT: 'mfrc522 挂起'
        
    });
    return Blockly;
}

exports = addMsg;
