/* eslint-disable func-style */
/* eslint-disable max-len */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        KS_VARIABLE_LABEL:'Variable Type',
        KS_variables_declare:'Declare %1 variable Type %2 Name %3 Assigned to %4',
        KS_variables_set:'Set %1 variable by %2',
        KS_variables_change:'Change %1 variable mode %2',
        KS_variables_value: 'variable %1',
        KS_variables_setString:'Set %1 String variable by %2',
        KS_global:'Global',
        KS_local:'Local',
        KS_MATH_INT: 'int',
        KS_MATH_LONG: 'long',
        KS_MATH_FLOAT: 'float',
        KS_MATH_BOOLEAN: 'boolean',
        KS_MATH_BYTE: 'byte',
        KS_MATH_CHAR: 'char',
        KS_MATH_STRING: 'string',
        KS_MATH_UNSIGNED_INT: 'unsigned int',
        KS_MATH_WORD: 'word',
        KS_MATH_UNSIGNED_LONG: 'unsigned long',
        KS_MATH_UNSIGNED_CHAR: 'unsigned char',
        KS_MATH_DOUBLE: 'double',

        KS_TEXT_LABEL:'TEXT',
        KS_char: 'char%1',
        KS_string: 'string%1',
        KS_data: '%1',

        KS_LOGIC_LABEL:'logic',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED pin%1 out%2',
        LED_ANALOG: 'LED %1 channel%2 analogWrite%3',
        ATBUZZER_CATEGORY: 'Buzzer',
        ATBUZZER_STATE: 'buzzer pin%1 out%2',
        BUZZER_CATEGORY: 'Speaker',
        BUZZER_TONE_D: 'Tone PIN#%1 frequency%2 duration%3',
        BUZZER_MUSIC: 'Tone PIN#%1 play music%2',
        BUZZER_NOTONE: 'NoTone%1',
        BUTTON_CATEGORY: 'Button',
        BUTTON_READ_STATE: 'Interface %1 button was be pushed？',
        BUTTON_READ_VALUE: 'The state value of button in interface %1',
        PIR_CATEGORY: 'PIR',
        PIR_READ_VALUE: 'Read interface %1 PIR motion sensor',
        LIGHTSENSOR_CATEGORY: 'Light',
        LIGHTSENSOR_READ_VALUE: 'read the value of light %1',
        POTSENSOR_CATEGORY: 'Pot',
        POTSENSOR_READ_VALUE: 'read the value of pot %1',
        SOUNDSENSOR_CATEGORY: 'Sound',
        SOUNDSENSOR_READ_VALUE: 'read the value of sound %1',
        HC_SR04_CATEGORY: 'Ultrasonic',
        HC_SR04_READ_DISTANCE: 'HC-SR04 trig pin %1 echo pin %2 read distance %3',
        DHT_CATEGORY: 'DHT11',
        DHT_INIT: 'init dht11 %1 pin %2 mode %3',
        DHT_READ_TEMPERATURE: 'dht11 %1 read temperature %2',
        DHT_READ_HUMIDITY: 'dht11 %1 read humidity',
        KS_SERVO_CATEGORY: 'Servo',
        KS_SERVO_ANGLE: 'servo PIN#%1 channel%2 degree%3 delay%4',
        KS_SERVO_READ: 'servo PIN#%1 read degree',
        WS2812B_CATEGORY: 'RGB LED',
        WS2812B_INIT: 'pin %1 %2 RGB LEDs',
        WS2812B_SETBRIGHTNESS: 'pin %1 LED brightness %2',
        WS2812B_CLEAR: 'pin %1 clear all LEDs',
        WS2812B_SETRANGECOLOR: 'pin %1 RGB %2 to %3 show color %4',
        WS2812B_RGBTOCOLOR: 'red %1 green %2 blue %3',
        WS2812B_SHOWRAINBOW: 'pin %1 %2 to %3 RGB LEDs show  a gradient color from %4 to %5',
        WS2812B_SHIFT: 'pin %1 shift pixels by %2',
        WS2812B_ROTATE: 'pin %1 rotate pixels by %2',
        WS2812B_SHOWBARGRAPH: 'pin %1 %2 to %3 RGB LEDs show histogram current value: %4 max value: %5',
        TM1650_CATEGORY: 'Digital tube',
        TM1650_INIT: 'init TM1650 4-bit digital tube %1',
        TM1650_SCREENSET:'TM1650 4-bit digital %1 %2',
        TM1650_SHOW: 'TM1650 4-bit digital tube %1 show %2',
        TM1650_SETDOT:'%3 the %2 decimal point of TM1650 4-bit digital tube %1',
        TM1650_ON: 'open',
        TM1650_OFF: 'close',
        TM1650_CLEAR: 'clear',
        TM1650_LIGHT: 'brighten',
        TM1650_UNLIGHT: 'darken',
        TM1650_1: '1',
        TM1650_2: '2',
        TM1650_3: '3',
        TM1650_4: '4',
        LCD_CATEGORY: 'LCD',
        LCD_INIT: 'init lcd I2C address %1',
        LCD_SETCURSORPOSITION: 'set lcd cursor position x: %1 y: %2',
        LCD_PRINT: 'lcd print %1',
        LCD_CLEAR: 'clear lcd',
        LCD_SETBACKLIGHT: 'set lcd back light %1',
        LCD_SATE_ON: 'on',
        LCD_SATE_OFF: 'off',
        LCD_SETCURSORSTYLE: 'set lcd cursor %1 style %2',
        LCD_SATE_DISPLAY: 'display',
        LCD_SATE_HIDE: 'hide',
        LCD_STYLE_BLINK: 'blink',
        LCD_STYLE_NOBLINK: 'no-blink',
        MATIRXDISPLAY_CATEGORY: 'Matrix',
        MATIRXDISPLAY_INIT: 'init matrix display pin CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: 'pin DIN to MOSI and CLK to SCK.',
        MATIRXDISPLAY_DRAWPIXEL: 'martix display draw pixel x: %1 y: %2 color %3',
        MATIRXDISPLAY_COLOR_RED: 'red',
        MATIRXDISPLAY_COLOR_BLACK: 'black',
        MATIRXDISPLAY_DRAWLINE: 'martix display draw line x0: %1 y0: %2, x1: %3 y1: %4 color %5',
        MATIRXDISPLAY_SHOWCHAR: 'martix display show char %1 color %2',
        MATIRXDISPLAY_SHOWNUMBER: 'martix display show number %1 color %2',
        MATIRXDISPLAY_FILL: 'martix display fill color %1',
        MATIRXDISPLAY_REFRESH: 'refresh the display of martix display',
        MATIRXDISPLAY_SETBRIGHTNESS: 'martix display set brightness %1',
        MATIRXDISPLAY_SETROTATION: 'martix display set rotation %1',
        IR_CATEGORY: 'IR Remote',
        IR_INIT: 'IR remote init PIN#%1',
        IR_DATA: 'Received data',
        IR_READ: 'Read the data',
        IR_REFRESH: 'Refresh data',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: 'wifi connect ssid:%1 password:%2',
        WIFI_READ: 'WiFi read',
   
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        KS_VARIABLE_LABEL:'变量类型',
        KS_variables_declare:'声明 %1 数字变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_declare2:'声明 %1 字符串变量 类型 %2 名称 %3 赋值为 %4',
        KS_variables_set:'设置 %1 变量 为 %2',
        KS_variables_change:'设置 %1 变量 模式 %2',
        KS_variables_value: '变量 %1',
        KS_variables_setString:'设置 %1 字符串变量 为 %2',
        KS_global:'全局',
        KS_local:'局部',
        KS_MATH_INT: '整数',
        KS_MATH_LONG: '长整数',
        KS_MATH_FLOAT: '小数',
        KS_MATH_BOOLEAN: '布尔',
        KS_MATH_BYTE: '字节',
        KS_MATH_CHAR: '字符',
        KS_MATH_STRING: '字符串',
        KS_MATH_UNSIGNED_INT: '无符号整数',
        KS_MATH_WORD: '字',
        KS_MATH_UNSIGNED_LONG: '无符号长整数',
        KS_MATH_UNSIGNED_CHAR: '无符号字符',
        KS_MATH_DOUBLE: '双精度浮点数',

        KS_TEXT_LABEL:'文本',
        KS_char: '\'%1\'',
        KS_string: '\"%1\"',
        KS_data: '%1',

        KS_LOGIC_LABEL:'逻辑',
        KS_judge:'%1 %2 %3',
        LED_CATEGORY: 'LED',
        LED_SET_LED_STATE: 'LED 接口%1 输出%2 ',
        LED_ANALOG: 'LED灯 %1 通道%2 模拟输出%3',
        ATBUZZER_CATEGORY: '有源蜂鸣器',
        ATBUZZER_STATE: '蜂鸣器 接口%1 输出%2 ',
        BUZZER_CATEGORY: '扬声器',
        BUZZER_TONE_D: '播放声音 引脚%1 频率%2 节拍%3',
        BUZZER_MUSIC: '扬声器 引脚%1 播放音乐%2',
        BUZZER_NOTONE: '结束声音 引脚%1',
        BUTTON_CATEGORY: '按键开关',
        BUTTON_READ_STATE: '接口%1按钮被按下？',
        BUTTON_READ_VALUE: '接口%1按钮的状态值',
        PIR_CATEGORY: '人体红外传感器',
        PIR_READ_VALUE: '读取接口 %1 红外热释电传感器',
        LIGHTSENSOR_CATEGORY: '光线传感器',
        LIGHTSENSOR_READ_VALUE: '读取接口%1光线强度',
        POTSENSOR_CATEGORY: '可调电阻模块',
        POTSENSOR_READ_VALUE: '读取接口%1电阻值',
        SOUNDSENSOR_CATEGORY: '声音传感器',
        SOUNDSENSOR_READ_VALUE: '读取接口%1声音数值',
        HC_SR04_CATEGORY: '超声波传感器',
        HC_SR04_READ_DISTANCE: '超声波传感器 trig 引脚 %1 echo 引脚 %2 读取距离 %3',
        DHT_CATEGORY: '温湿度',
        DHT_INIT: '初始化 温湿度 %1 引脚 %2 型号 %3',
        DHT_READ_TEMPERATURE: '温湿度 %1 读取温度 %2',
        DHT_READ_HUMIDITY: '温湿度 %1 读取湿度',
        KS_SERVO_CATEGORY: '舵机',
        KS_SERVO_ANGLE: '舵机 引脚%1 通道%2 角度%3 延时(毫秒)%4',
        KS_SERVO_READ: '舵机 引脚%1 读取度数',
        WS2812B_CATEGORY: 'RGB灯',
        WS2812B_INIT: '初始化 RGB灯 接口 %1 灯总数 %2',
        WS2812B_SETBRIGHTNESS: 'RGB灯 设置接口 %1 灯带亮度为 %2',
        WS2812B_CLEAR: 'RGB灯 接口 %1 全部熄灭',
        WS2812B_SETRANGECOLOR: 'RGB灯 接口 %1 灯号 %2 到 %3 显示颜色 %4',
        WS2812B_RGBTOCOLOR: '红 %1 绿 %2 蓝 %3',
        WS2812B_SHOWRAINBOW: 'RGB灯 接口 %1 灯号 %2 到 %3 显示渐变颜色 色调从 %4 到 %5',
        WS2812B_SHIFT: 'RGB灯 接口 %1 移动 %2 单位',
        WS2812B_ROTATE: 'RGB灯 接口 %1 循环移动 %2 单位',
        WS2812B_SHOWBARGRAPH: 'RGB灯 接口 %1 灯号 %2 到 %3 显示柱状图 当前值 %4 最大值 %5',
        TM1650_CATEGORY: '四位数码管',
        TM1650_INIT: '初始化TM1650四位数码管 %1',
        TM1650_SCREENSET:'TM1650四位数码管 %1 %2',
        TM1650_SHOW: 'TM1650四位数码管 %1 显示 %2',
        TM1650_SETDOT:'TM1650四位数码管 %1 第 %2 个小数点 %3',
        TM1650_ON: '开',
        TM1650_OFF: '关',
        TM1650_CLEAR: '清屏',
        TM1650_LIGHT: '亮',
        TM1650_UNLIGHT: '暗',
        TM1650_1: '1',
        TM1650_2: '2',
        TM1650_3: '3',
        TM1650_4: '4',
        LCD_CATEGORY: '1602显示屏',
        LCD_INIT: '初始化 显示屏 I2C 地址 %1',
        LCD_SETCURSORPOSITION: 'set 显示屏 光标位置 x: %1 y: %2',
        LCD_PRINT: '显示屏 打印 %1',
        LCD_CLEAR: '清空 显示屏',
        LCD_SETBACKLIGHT: '设置 显示屏 背光 %1',
        LCD_SATE_ON: '开',
        LCD_SATE_OFF: '关',
        LCD_SETCURSORSTYLE: '设置 显示屏 光标 %1 样式 %2',
        LCD_SATE_DISPLAY: '显示',
        LCD_SATE_HIDE: '隐藏',
        LCD_STYLE_BLINK: '闪烁',
        LCD_STYLE_NOBLINK: '不闪烁',
        MATIRXDISPLAY_CATEGORY: '点阵屏',
        MATIRXDISPLAY_INIT: '初始化点阵屏引脚 CS %1',
        MATIRXDISPLAY_INIT_TOOLTIP: '引脚 DIN 接 MOSI， CLK 接 SCK。',
        MATIRXDISPLAY_DRAWPIXEL: '点阵屏绘制点 x: %1 y: %2 颜色 %3',
        MATIRXDISPLAY_COLOR_RED: '红色',
        MATIRXDISPLAY_COLOR_BLACK: '黑色',
        MATIRXDISPLAY_DRAWLINE: '点阵屏绘制直线 x0: %1 y0: %2, x1: %3 y1: %4 颜色 %5',
        MATIRXDISPLAY_SHOWCHAR: '点阵屏显示字符 %1 颜色 %2',
        MATIRXDISPLAY_SHOWNUMBER: '点阵屏显示数字 %1 颜色 %2',
        MATIRXDISPLAY_FILL: '点阵屏填充颜色 %1',
        MATIRXDISPLAY_REFRESH: '刷新点阵屏显示',
        MATIRXDISPLAY_SETBRIGHTNESS: '点阵屏设置亮度 %1',
        MATIRXDISPLAY_SETROTATION: '点阵屏设置旋转 %1',
        IR_CATEGORY: '红外接收',
        IR_INIT: '初始化红外接收 引脚%1',
        IR_DATA: '接收到红外遥控的数据',
        IR_READ: '读取红外接收数据',
        IR_REFRESH: '刷新红外接收数据',
        WIFI_CATEGORY: 'ESP32 WIFI',
        WIFI_INIT: '连接WiFi 名称%1 密码%2',
        WIFI_READ: 'WiFi 读取数据',
        
    });
    return Blockly;
}

exports = addMsg;
